<?php

namespace Auth\Entity;

use Auth\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * AuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param Usario $usuario
     * @param $login
     * @param $password
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByLoginAndPassword(User $usuario, $login, $password)
    {
        $userLogin = $this
            ->createQueryBuilder('u')
            ->where('u.login = :a1')
            ->setParameter('a1', $login)
            ->getQuery()
            ->getOneOrNullResult();

        if (!is_null($userLogin)) {
            return $userLogin;
        }
        return false;
    }
}
